spring:
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db-changelog-master.xml
  datasource:
    url: jdbc:sqlserver://XXX:1433;databaseName=XX;user=SA;password=Password
    user: SA
    password: XXX
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect
  cache:
    type: none
server:
  port: 8085
